### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by abdullaaaah** [abdullaaaah/gpa-calculator#11]
It may be helpful to have a minimum grade in the final mark widget, 
Example of minimum grade:
You've had two assignments
**ASSIGNMENT 1** 

- mark => 100%
- weight => 10

**ASSIGNMENT 2**
- mark => 50%
- weight => 10

Based on this information, your current minimum grade is 15% out of 100% in total.

**Comment by krhobeck** [comment]
Feature Implemented.
