### ISSUE TITLE
Input rows not loading on 'CSC108'

### ISSUE THREAD

**Issue by krhobeck** [abdullaaaah/gpa-calculator#2]
<img width="1420" alt="Screen Shot 2020-12-24 at 10 12 52 PM" src="https://user-images.githubusercontent.com/37283880/103116697-52206d80-4635-11eb-8d7c-f076fc04f659.png">

Steps to recreate:

Run GPA calculator
Click on the CSC108 tab

**Comment by abdullaaaah** [comment]
Fixed
