### ISSUE TITLE
Instance of Class changes background text of input?

### ISSUE THREAD

**Issue by krhobeck** [abdullaaaah/gpa-calculator#3]
<img width="1420" alt="Screen Shot 2020-12-24 at 10 12 52 PM" src="https://user-images.githubusercontent.com/37283880/103116885-fdc9bd80-4635-11eb-8614-bbd7236f1cd5.png">

Steps to recreate:

Run App calculator from python
Click into CSC108 class

Fix:
Update input text itself not the placeholder

(unless this was intended)

**Comment by abdullaaaah** [comment]
Seems to be fine for me with the latest version, check again?

**Comment by abdullaaaah** [comment]
Closing, re-open if issue persists
