### ISSUE TITLE
UX: Dynamic colors in chart

### ISSUE THREAD

**Issue by abdullaaaah** [abdullaaaah/gpa-calculator#6]
<img width="774" alt="Screen Shot 2021-01-02 at 10 01 08 PM" src="https://user-images.githubusercontent.com/12470207/103470859-0745da80-4d46-11eb-9a37-2c26d9af7144.png">

The colour of the graph should be based on the performance. 
the green we are using: #006622
the red we are using: #b30000
the blue we are using: #071136

**Comment by abdullaaaah** [comment]
Point graph should also be the dark blue we are using

**Comment by krhobeck** [comment]
Fixed.
